name: deploy

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to shuttle.rs
      run: cargo shuttle login --api-key ${{secrets.SHUTTLE_API_KEY}}
    - name: Create secrets.toml
      run: echo "DISCORD_TOKEN=\"${{secrets.DISCORD_TOKEN}}\"">secrets.toml
    - name: Deploy to shuttle
      run: cargo shuttle deploy
